### ISSUE TITLE
what happened to http://127.0.0.1:43110/1MiS3ud9JogSQpd1QVmM6ETHRmk5RgJn6E

### ISSUE THREAD

**Issue by kotenok2000** [krixano/ImportantZites#8]
what happened to http://127.0.0.1:43110/1MiS3ud9JogSQpd1QVmM6ETHRmk5RgJn6E

**Comment by imachug** [comment]
I'm amused you've missed that ZeroTalk thread... You'd better read it: http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1557305635_16HcyFK8526ZYJBKPpSDCbpJv6WWBNvENj
